# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27cd7c39f04014db9ef8d4d1baab22cc07fa8d0fc7719d580ba015fb2167d940ac0438e490070af1b4750f5b584701038b02e79c22c86bbc0e1c8e4cb28fd337

test:
  secret_key_base: 68a5911548ea815cb7e67061d31d3b59cac154f7dfc03dcf96546df18feea968728d6f08f2b6d1aa5d0151d22cdb321da77b7985bf2661458c4d1bd40fe93889

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
